---

- name: Install qemu-system-x86
  ansible.builtin.yum:
    name:
      - qemu-system-x86
    state: present
    update_cache: true
  when: (lisoq_qemu_install)

- name: Install rsync
  ansible.builtin.yum:
    name:
      - rsync
    state: present
  when: (lisoq_iso_file_local) or (lisoq_qemu_static_custom_local)

- name: Run commands before install iptables
  raw: "{{ item }}"
  loop:
    - systemctl stop firewalld
  ignore_errors: true
  when: (lisoq_firewall_acl_enable)

- name: Install iptables
  ansible.builtin.yum:
    name:
      - iptables-services
  when: (lisoq_firewall_acl_enable)

- name: Starting iptables services after installation
  ansible.builtin.systemd:
    name: '{{ services }}'
    state: started
    enabled: true
  with_items:
    - iptables
    - ip6tables
  loop_control:
    loop_var: services
  when: (lisoq_firewall_acl_enable)
