---

# source:
# https://github.com/redhat-openstack/ansible-role-tripleo-parts/blob/master/parts/kvm/tasks/main.yml

# Grab CPU flags from `/proc/cpuinfo` and put the result into the
# `cpu_flags_cmd` variable.
- name: get cpu flags
  command: >
    awk -F: '/^flags/ {print $2; exit}' /proc/cpuinfo
  register: lisoq_cpu_flags_cmd

# Extract the flags into a list variable named `cpu_flags`.
- name: set cpu flags fact
  set_fact:
    lisoq_cpu_flags: "{{ lisoq_cpu_flags_cmd.stdout.split() }}"

# Identify the processor manufacturer by looking for "Intel" or "AMD"
# in `/proc/cpuinfo`.
- name: check if Intel processor
  command: grep -q Intel /proc/cpuinfo
  ignore_errors: true
  register: lisoq_cpu_is_intel

- name: check if AMD processor
  command: grep -q AMD /proc/cpuinfo
  ignore_errors: true
  register: lisoq_cpu_is_amd

# Enable [nested virtualization][nested]. Set the `lisoq_nested_virt` fact
# to `true` if we have Intel processors and the `vmx` flag or we have
# AMD processors and the `svm` flag.
#
# [nested]: https://www.kernel.org/doc/Documentation/virtual/kvm/nested-vmx.txt
- name: set lisoq_nested_virt fact
  set_fact:
    lisoq_nested_virt: >-
      {{ ((lisoq_cpu_is_intel and 'vmx' in lisoq_cpu_flags)
      or (lisoq_cpu_is_amd and 'svm' in lisoq_cpu_flags))|bool }}
  when: (lisoq_cpu_flags is defined) and (lisoq_cpu_flags)

# Immediately load the appropriate kvm vendor module.
- name: load kvm module [intel]
  command: modprobe kvm_intel
  when: (lisoq_cpu_is_intel is defined) and (lisoq_cpu_is_intel is success)

- name: load kvm module [amd]
  command: modprobe kvm_amd
  when: (lisoq_cpu_is_amd is defined) and (lisoq_cpu_is_amd is success)
